services:
  netalertx:
    privileged: true
    build:
      dockerfile: Dockerfile
      context: .
      cache_from:
        - type=registry,ref=docker.io/jokob-sk/netalertx:buildcache
    container_name: netalertx
    network_mode: host
    # restart: unless-stopped
    volumes:
      # - ${APP_DATA_LOCATION}/netalertx_dev/config:/app/config
      - ${APP_DATA_LOCATION}/netalertx/config:/app/config
      # - ${APP_DATA_LOCATION}/netalertx_dev/db:/app/db      
      - ${APP_DATA_LOCATION}/netalertx/db:/app/db           
      # (optional) useful for debugging if you have issues setting up the container
      - ${APP_DATA_LOCATION}/netalertx/log:/app/log      
      # (API: OPTION 1) use for performance
      - type: tmpfs
        target: /app/api
    environment:      
      # - APP_CONF_OVERRIDE={"SCAN_SUBNETS":"['192.168.1.0/24 --interface=eth1']","GRAPHQL_PORT":"20223","UI_theme":"Light"}
      - TZ=${TZ}
      - PORT=${PORT}      
      # ❗ DANGER ZONE BELOW - Setting ALWAYS_FRESH_INSTALL=true will delete the content of the /db & /config folders
      # - ALWAYS_FRESH_INSTALL=${ALWAYS_FRESH_INSTALL}
      # - LOADED_PLUGINS=["DHCPLSS","PIHOLE","ASUSWRT","FREEBOX"]
      
